version: "3.8"

services:
  wsddb:
    container_name: wsddb
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wsdebiz

  wsdapp:
    container_name: wsdapp
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - wsddb
